application: atanproto
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /image
  static_dir: static/image
- url: /.*
  script: app/main.py
  login: required
